on:
  push:
    branches:
      - main

    paths-ignore:
      - README.md
      - 'diagrams/**'

jobs:
  terraform-validation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Obrigatório para o OIDC funcionar
      contents: read  # Permite que o checkout leia o código do repositório


    steps:
      - name: deploying machine
        uses: actions/checkout@v4

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::341208406073:role/event-driven-oicd-role # trocar para funcionar dinamicamente
          aws-region: sa-east-1 # trocar para funcionar dinamicamente

      - name: Configuring Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Testing AWS connection
        run: aws sts get-caller-identity

      - name: deploying AWS
        run: |
          terraform init
          terraform fmt -check
          terraform validate
          terraform plan
          terraform apply -auto-approve